
- hosts: primary

  tasks:
    - name: create work-dir
      file:
        path: /opt/workdir
        state: directory
      become: True

    - name: create test-ci-job-pre file
      file:
        path: /opt/workdir/pre.txt
        state: touch
      become: True
