
- hosts: all

  tasks:
    - name: start zuul console
      zuul_console:

- hosts: localhost

  tasks:
    - name: set logdir
      set_fact:
        log_dir: "/opt/logdir/{{ zuul.project.name }}/{{ zuul.change }}/{{ zuul.build }}/{{ zuul.patchset }}"

    - name: create logdir
      file:
        path: "{{ log_dir }}"
        state: directory

- hosts: primary

  tasks:
    - name: pre task
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items: ["curl", "wget", "vim"]
      become: True

    - name: print zuul var content
      debug:
        msg: "{{ zuul | to_nice_yaml }}"
