
- hosts: primary

  tasks:
    - name: start zuul console
      zuul_console:

    - name: pre task
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items: ["curl", "wget", "vim"]
      become: True

    - name: print zuul var content
      debug:
        msg: "{{ zuul | to_nice_yaml }}"
